# Generated by Django 3.0.6 on 2020-05-14 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('yrsold', models.DecimalField(decimal_places=0, max_digits=3)),
                ('skills', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
