# Generated by Django 2.2.1 on 2020-06-29 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agile', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agile',
            options={'managed': True},
        ),
    ]
