# Generated by Django 2.2.1 on 2020-05-26 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agile', '0002_auto_20200525_1529'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agile',
            name='id',
        ),
        migrations.AlterField(
            model_name='agile',
            name='title',
            field=models.TextField(blank=True, primary_key=True, serialize=False),
        ),
    ]
