# Generated by Django 2.2.1 on 2020-07-13 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agile', '0002_auto_20200630_0206'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('times', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='agile',
            name='id',
        ),
        migrations.AddField(
            model_name='agile',
            name='index',
            field=models.IntegerField(default='don', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='agile',
            name='title',
            field=models.TextField(blank=True, default='don'),
        ),
        migrations.AlterModelTable(
            name='agile',
            table='agile_story',
        ),
    ]
