# Generated by Django 2.2.1 on 2020-07-06 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agile', '0002_auto_20200630_0206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agile',
            name='id',
        ),
        migrations.AddField(
            model_name='agile',
            name='index',
            field=models.IntegerField(default='don', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='agile',
            name='title',
            field=models.TextField(blank=True),
        ),
        migrations.AlterModelTable(
            name='agile',
            table='agile_story',
        ),
    ]
