# Generated by Django 2.2.1 on 2020-05-27 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agile', '0003_auto_20200527_0025'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='agile',
            table='default',
        ),
    ]
