# Generated by Django 2.2.1 on 2020-05-31 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agile', '0004_auto_20200527_1527'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='agile',
            table='agiledb',
        ),
    ]
