# Generated by Django 2.2.1 on 2020-07-07 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agile', '0004_register_create'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='register_create',
            new_name='Register',
        ),
    ]
