# Generated by Django 2.2.1 on 2020-05-31 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agile', '0007_auto_20200531_1911'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='agile',
            table='agile',
        ),
    ]
