# Generated by Django 2.2.1 on 2020-06-02 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agile', '0008_auto_20200531_1921'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='agile',
            table='agiledb',
        ),
    ]
