# Generated by Django 2.2.1 on 2020-06-02 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agile', '0009_auto_20200602_1649'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='agile',
            table='agile',
        ),
    ]
