# Generated by Django 2.2.1 on 2020-06-02 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agile', '0010_auto_20200602_1701'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='agile',
            table='agiledb',
        ),
    ]
