# Generated by Django 2.2.1 on 2020-06-02 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agile', '0012_auto_20200602_2346'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Agile',
        ),
    ]
