# Generated by Django 2.2.1 on 2020-06-04 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agile', '0013_delete_agile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agile',
            fields=[
                ('title', models.TextField(blank=True, primary_key=True, serialize=False)),
                ('content', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'agile',
                'managed': True,
            },
        ),
    ]
