# Generated by Django 2.2.1 on 2020-06-17 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agile', '0014_agile'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='agile',
            table='agile_story',
        ),
    ]
